services:
  redis:
    image: redis:7
    container_name: redis_second
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: service
    ports:
      - "5434:5432"

volumes:
  redis_data: