"""refactor

Revision ID: 533e7fc6dd2d
Revises: e08486bb7951
Create Date: 2026-01-12 17:38:38.011875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533e7fc6dd2d'
down_revision: Union[str, Sequence[str], None] = 'e08486bb7951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'bio')
    op.drop_column('profile', 'title')
    op.drop_column('user', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('profile', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('profile', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
